/* ── INITIAL STATE ── */
const INITIAL_TRUTHS = [
  { id: 1, truth: "The confidence you perceive in others is mostly performance.", category: "Psychology", votes: 42 },
  { id: 2, truth: "Most of your opinions were formed to fit in, not from thinking.", category: "Society", votes: 38 },
  { id: 3, truth: "The algorithm knows what you want before you do, and you let it.", category: "Tech", votes: 55 },
  { id: 4, truth: "Convenience has slowly replaced almost every form of discipline.", category: "Life", votes: 89 },
  { id: 5, truth: "You are not afraid of failure. You are afraid of other people watching you fail.", category: "Psychology", votes: 102 },
  { id: 6, truth: "Nostalgia is a liar that insists things were better than they actually were.", category: "Life", votes: 27 },
  { id: 7, truth: "We built the internet to connect the world, but it mostly just isolated us in bespoke echo chambers.", category: "Tech", votes: 64 },
  { id: 8, truth: "You will spend most of your life working to buy things you don't have time to use.", category: "Society", votes: 115 },
  { id: 9, truth: "Intelligence is often just the ability to rationalize terrible decisions elegantly.", category: "Philosophy", votes: 33 },
  { id: 10, truth: "If someone tells you exactly what you want to hear, you are being sold something.", category: "Life", votes: 77 },
  { id: 11, truth: "Outrage is addictive, and you are likely heavily dependent on it.", category: "Psychology", votes: 48 },
  { id: 12, truth: "You probably don't need a life hack. You probably just need to go to sleep.", category: "Life", votes: 150 },
  { id: 13, truth: "History is written by the victors, but the future is written by the algorithms.", category: "Tech", votes: 21 },
  { id: 14, truth: "People don't want the truth. They want a lie that sounds like the truth.", category: "Philosophy", votes: 94 },
  { id: 15, truth: "You are the villain in someone else's story, and there is nothing you can do about it.", category: "Life", votes: 105 }
];

let apiKey = '';
let isFetching = false;
let truthCounter = 15;
let upvotesToday = parseInt(localStorage.getItem('scroll_upvotes')) || 0;
let userVotes = JSON.parse(localStorage.getItem('scroll_user_votes')) || {}; // { id: 'up'/'down' }

// DOM
const screenApi = document.getElementById('screen-api');
const screenScroll = document.getElementById('screen-scroll');
const feed = document.getElementById('truthFeed');
const scrollTrigger = document.getElementById('scrollTrigger');
const modal = document.getElementById('submitModal');
const truthInput = document.getElementById('truthInput');
const truthCategory = document.getElementById('truthCategory');
const modalLoading = document.getElementById('modalLoading');
const modalResult = document.getElementById('modalResult');
const btnSubmitTruth = document.getElementById('btnSubmitTruth');

// Init
document.addEventListener('DOMContentLoaded', () => {
  const savedKey = localStorage.getItem('claude_api_key_scroll');
  if (savedKey) document.getElementById('apiKeyInput').value = savedKey;
});

function initApp() {
  const key = document.getElementById('apiKeyInput').value.trim();
  if (!key) { alert('A key is required to unfurl the scroll.'); return; }
  apiKey = key;
  localStorage.setItem('claude_api_key_scroll', key);
  startScroll();
}

function skipToOffline() {
  apiKey = null;
  startScroll();
  scrollTrigger.innerHTML = '<div class="loader-text">The oracle slumbers. No new truths will be generated.</div>';
}

function startScroll() {
  screenApi.classList.remove('active');
  screenScroll.classList.add('active');
  
  // Render Initial
  INITIAL_TRUTHS.forEach(t => renderTruth(t));
  
  // Render local custom truths if any
  const custom = JSON.parse(localStorage.getItem('scroll_custom_truths')) || [];
  custom.forEach(t => renderTruth(t));
  
  // Setup Observer
  if (apiKey) {
    const observer = new IntersectionObserver((entries) => {
      if (entries[0].isIntersecting && !isFetching) {
        fetchNewTruths();
      }
    }, { rootMargin: '200px' });
    observer.observe(scrollTrigger);
  }

  initAudio();
}

/* ── RENDERING ── */
function renderTruth(t) {
  const isDisputed = t.votes < 0;
  const userVote = userVotes[t.id];
  
  const card = document.createElement('div');
  card.className = `truth-card ${isDisputed ? 'disputed' : ''}`;
  card.id = `truth-${t.id}`;
  
  let tooRealBadge = t.votes >= 10 ? `<span class="badge badge-too-real">Too Real</span>` : '';
  
  card.innerHTML = `
    <div class="truth-meta">
      <div>
        <span class="badge">${t.category}</span>
        ${tooRealBadge}
      </div>
      <div style="font-family: 'Inter'; text-transform: none; color: #a8a29e;">Generated by API</div>
    </div>
    <div class="disputed-label">⚠️ Disputed Truth</div>
    <div class="truth-text">${t.truth}</div>
    <div class="truth-actions">
      <button class="vote-btn up ${userVote === 'up' ? 'active' : ''}" onclick="castVote(${t.id}, 'up')">↑ <span id="vcount-${t.id}">${t.votes}</span></button>
      <button class="vote-btn down ${userVote === 'down' ? 'active' : ''}" onclick="castVote(${t.id}, 'down')">↓</button>
      <button class="vote-btn" onclick="shareTruth('${t.truth.replace(/'/g, "\\'")}')">➦ Share</button>
    </div>
  `;
  
  feed.appendChild(card);
  
  // Fade in
  setTimeout(() => card.classList.add('visible'), 50);
}

/* ── VOTING ── */
function castVote(id, direction) {
  const el = document.getElementById(`truth-${id}`);
  const countEl = document.getElementById(`vcount-${id}`);
  let currentCount = parseInt(countEl.textContent);
  
  const currentVote = userVotes[id];
  
  if (currentVote === direction) {
    // Unvote
    delete userVotes[id];
    currentCount += (direction === 'up' ? -1 : 1);
    el.querySelector(`.vote-btn.${direction}`).classList.remove('active');
  } else {
    // Vote
    if (currentVote) {
      // Switch vote
      currentCount += (direction === 'up' ? 2 : -2);
      el.querySelector(`.vote-btn.${currentVote}`).classList.remove('active');
    } else {
      // New vote
      currentCount += (direction === 'up' ? 1 : -1);
      if (direction === 'up') {
        upvotesToday++;
        localStorage.setItem('scroll_upvotes', upvotesToday);
      }
    }
    userVotes[id] = direction;
    el.querySelector(`.vote-btn.${direction}`).classList.add('active');
  }
  
  countEl.textContent = currentCount;
  localStorage.setItem('scroll_user_votes', JSON.stringify(userVotes));
  
  // Blur logic
  if (currentCount < 0) el.classList.add('disputed');
  else el.classList.remove('disputed');
}

function shareTruth(text) {
  navigator.clipboard.writeText(`"${text}" - The Scroll of Truth`);
  alert('Truth copied to clipboard.');
}

/* ── CLAUDE API INTEGRATION ── */
async function fetchNewTruths() {
  isFetching = true;
  scrollTrigger.style.opacity = '1';
  
  const prompt = `Generate 3 uncomfortable but true observations about modern life, human psychology, or technology. Make them profound, not preachy. Short (15-30 words each). Reply ONLY with a raw JSON array of objects, no markdown formatting or introduction. Format: [{"truth": "...", "category": "Philosophy|Tech|Society|Life|Science"}]. Do not wrap in \`\`\`json.`;

  try {
    const res = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
        'anthropic-dangerous-direct-browser-access': 'true'
      },
      body: JSON.stringify({
        model: "claude-3-haiku-20240307",
        max_tokens: 300,
        messages: [{ role: "user", content: prompt }]
      })
    });

    if (!res.ok) throw new Error('API Error');
    const data = await res.json();
    
    let text = data.content[0].text.trim();
    // Strip markdown if it snuck in
    if (text.startsWith('```json')) text = text.substring(7);
    if (text.endsWith('```')) text = text.substring(0, text.length - 3);
    
    const newTruths = JSON.parse(text);
    
    newTruths.forEach(t => {
      truthCounter++;
      renderTruth({ id: truthCounter, truth: t.truth, category: t.category, votes: 0 });
    });
    
  } catch (e) {
    console.error(e);
    scrollTrigger.innerHTML = '<div class="loader-text" style="color:var(--accent-red)">The oracle encountered an error connecting to the ether.</div>';
  }
  
  isFetching = false;
}

/* ── MODERATION SUBMISSION ── */
function openModal() { modal.classList.add('show'); }
function closeModal() { 
  modal.classList.remove('show'); 
  truthInput.value = '';
  modalResult.style.display = 'none';
  modalLoading.style.display = 'none';
  btnSubmitTruth.style.display = 'block';
}

async function submitTruth() {
  if (!apiKey) {
    alert("You are in offline mode. The oracle cannot judge your words.");
    return;
  }
  
  const text = truthInput.value.trim();
  if (!text) return;

  btnSubmitTruth.style.display = 'none';
  modalLoading.style.display = 'block';
  modalResult.style.display = 'none';

  const prompt = `Review this submitted truth: "${text}". Is this a genuine uncomfortable truth/observation, or is it hate speech, offensive, or nonsense? 
If it is valid, reply with a JSON object: {"valid": true, "improved": "slightly clearer version of the truth"}. 
If it is invalid or already a highly common cliché, reply: {"valid": false, "reason": "short reason"}. Reply ONLY with JSON.`;

  try {
    const res = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
        'anthropic-dangerous-direct-browser-access': 'true'
      },
      body: JSON.stringify({
        model: "claude-3-haiku-20240307",
        max_tokens: 200,
        messages: [{ role: "user", content: prompt }]
      })
    });

    const data = await res.json();
    let respText = data.content[0].text.trim();
    if (respText.startsWith('```json')) respText = respText.substring(7);
    if (respText.endsWith('```')) respText = respText.substring(0, respText.length - 3);
    
    const parsed = JSON.parse(respText);
    
    modalLoading.style.display = 'none';
    
    if (parsed.valid) {
      truthCounter++;
      const newObj = { id: truthCounter, truth: parsed.improved || text, category: truthCategory.value, votes: 1 };
      
      // Save locally
      const custom = JSON.parse(localStorage.getItem('scroll_custom_truths')) || [];
      custom.push(newObj);
      localStorage.setItem('scroll_custom_truths', JSON.stringify(custom));
      
      // Prepend to top
      const feedTop = document.getElementById('truthFeed').firstChild;
      feed.insertBefore(renderTruthDOM(newObj), feedTop);
      
      closeModal();
      window.scrollTo({ top: 0, behavior: 'smooth' });
    } else {
      modalResult.style.display = 'block';
      modalResult.textContent = parsed.reason || "The oracle rejected this truth.";
      btnSubmitTruth.style.display = 'block';
      btnSubmitTruth.textContent = "Try Again";
    }

  } catch (e) {
    modalLoading.style.display = 'none';
    modalResult.style.display = 'block';
    modalResult.textContent = "Error communicating with the oracle.";
    btnSubmitTruth.style.display = 'block';
  }
}

// Helper to return DOM node directly for prepend
function renderTruthDOM(t) {
  const card = document.createElement('div');
  card.className = `truth-card visible`;
  card.id = `truth-${t.id}`;
  card.innerHTML = `
    <div class="truth-meta">
      <div><span class="badge">${t.category}</span></div>
      <div style="font-family: 'Inter'; text-transform: none; color: #a8a29e;">Submitted by Anonymous 👤</div>
    </div>
    <div class="disputed-label">⚠️ Disputed Truth</div>
    <div class="truth-text">${t.truth}</div>
    <div class="truth-actions">
      <button class="vote-btn up" onclick="castVote(${t.id}, 'up')">↑ <span id="vcount-${t.id}">${t.votes}</span></button>
      <button class="vote-btn down" onclick="castVote(${t.id}, 'down')">↓</button>
    </div>
  `;
  return card;
}

/* ── WEB AUDIO AMBIENCE ── */
let audioEnabled = false;
let droneOsc, gainNode;

function toggleAudio() {
  if (!audioCtx) audioCtx = new (window.AudioContext || window.webkitAudioContext)();
  
  if (audioEnabled) {
    audioCtx.suspend();
    document.getElementById('audioToggle').style.opacity = '0.5';
  } else {
    audioCtx.resume();
    if (!droneOsc) startAmbience();
    document.getElementById('audioToggle').style.opacity = '1';
  }
  audioEnabled = !audioEnabled;
}

function startAmbience() {
  // 40Hz Drone
  droneOsc = audioCtx.createOscillator();
  gainNode = audioCtx.createGain();
  droneOsc.type = 'sine';
  droneOsc.frequency.value = 40; // Very low rumble
  gainNode.gain.value = 0.05;
  droneOsc.connect(gainNode).connect(audioCtx.destination);
  droneOsc.start();
  
  // Bell Toll Loop
  scheduleBell();
}

function scheduleBell() {
  const nextToll = Math.random() * 45000 + 45000; // 45-90s
  setTimeout(() => {
    playBell();
    scheduleBell();
  }, nextToll);
}

function playBell() {
  if (!audioCtx || audioCtx.state !== 'running') return;
  const t = audioCtx.currentTime;
  
  const osc1 = audioCtx.createOscillator();
  const osc2 = audioCtx.createOscillator();
  const osc3 = audioCtx.createOscillator();
  const gain = audioCtx.createGain();
  
  // Metallic detuned frequencies
  osc1.frequency.value = 150;
  osc2.frequency.value = 150 * 2.1;
  osc3.frequency.value = 150 * 3.14;
  
  osc1.connect(gain);
  osc2.connect(gain);
  osc3.connect(gain);
  gain.connect(audioCtx.destination);
  
  // Slow decay
  gain.gain.setValueAtTime(0, t);
  gain.gain.linearRampToValueAtTime(0.08, t + 0.1);
  gain.gain.exponentialRampToValueAtTime(0.001, t + 5);
  
  osc1.start(t); osc2.start(t); osc3.start(t);
  osc1.stop(t + 5); osc2.stop(t + 5); osc3.stop(t + 5);
}
